/**
 * This file was generated by farrow-api
 * Don't modify it manually
 */

import { apiPipeline } from 'farrow-api-client'

/**
 * {@label GreetInput}
 */
export type GreetInput = {
  /**
   * @remarks The name for greeting
   */
  name: string
}

/**
 * {@label GreetOutput}
 */
export type GreetOutput = {
  /**
   * @remarks The greeting came from server
   */
  greet: string
}

export const url = 'http://localhost:3003/api/greet'

export const api = {
  /**
   * @remarks Greeting
   */
  greet: (input: GreetInput) => apiPipeline.invoke(url, { path: ['greet'], input }) as Promise<GreetOutput>,
}
